export default {
    name: 'application',
    type: 'document',
    title: 'Application',
    fields: [
        { name: 'first_name', type: 'string', title: 'First Name' },
        { name: 'last_name', type: 'string', title: 'Last Name' },
        { name: 'title', type: 'string', title: 'Title' },
        { name: 'birthday', type: 'date', title: 'Birthday' },
        { name: 'sexe', type: 'string', title: 'Gender' },
        { name: 'familialSituation', type: 'string', title: 'Familial Situation' },
        { name: 'nationality', type: 'string', title: 'Nationality' },
        { name: 'currentCity', type: 'string', title: 'Current City' },
        { name: 'phoneNumber', type: 'string', title: 'Phone Number' },
        { name: 'alternativePhoneNumber', type: 'string', title: 'Alternative Phone Number' },
        { name: 'heareOption', type: 'string', title: 'Heard About Us' },
        { name: 'university', type: 'string', title: 'University' },
        { name: 'qualification', type: 'string', title: 'Qualification' },
        { name: 'subject', type: 'string', title: 'Subject' },
        { name: 'degreeTitle', type: 'string', title: 'Degree Title' },
        { name: 'debutDate', type: 'date', title: 'Start Date' },
        { name: 'endDate', type: 'date', title: 'End Date' },
        { name: 'cv', type: 'file', title: 'CV' },
        { name: 'diplome', type: 'file', title: 'Diploma' },
        { name: 'frenchLevel', type: 'string', title: 'French Level' },
        { name: 'arabicLevel', type: 'string', title: 'Arabic Level' },
        { name: 'englishLevel', type: 'string', title: 'English Level' },
        { name: 'readyToMove', type: 'string', title: 'Ready to Move' },
        { name: 'reasonToJoin', type: 'string', title: 'Reason to Join' },
        { name: 'opportunityVision', type: 'text', title: 'Opportunity Vision' },
    ],
};